site_name: CTF Gameserver
site_description: Documentation for FAUST CTF Gameserver
site_author: FAUST -- FAU Security Team
site_url: https://ctf-gameserver.org
repo_url: https://github.com/fausecteam/ctf-gameserver
# Disable "Edit in GitHub"
edit_uri: ''

theme:
  name: mkdocs
  nav_style: light
  # This would load third-party JavaScript, better disable it
  highlightjs: False

nav:
  - Home: index.md
  - Architecture: architecture.md
  - Installation: installation.md
  - Checkers:
    - General: checkers/index.md
    - checkers/python-library.md
    - checkers/go-library.md
  - Submission: submission.md
  - Observability: observability.md

# Use copyright field to add links to the footer
copyright: '<a href="https://faustctf.net/privacy/">Privacy</a> | <a href="https://faustctf.net/legal/">Legal</a>'

site_dir: docs_site
markdown_extensions:
  - toc:
      permalink: True
  - admonition
